language: php
php:
- 7.0
script:
- find . -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
deploy:
  provider: script
  script: deploy/deploy.sh
  on:
    tags: true
env:
  global:
  - SVN_REPOSITORY=https://plugins.svn.wordpress.org/wpmktgengine-extension-buddypress/
  - secure: Amp4Fvgm9sCj5l1mzSJlBT9V6mIcKqHiwAYIWOziAgHvTBIV/XqeQgSSBefLX2tlmrm/x0BZM/ox4tehegB5uBEHlMdZmcQGNzDGUwLh82dH22KWQIwIw6UgxWMhy5pskbtZfIn8XNBHWkG8wW3meR4EzTVzhMWKWSyDa225wZ+gJ3Y2qc6tC95Q0jTjyN0kfDnyZLM3DiDq/xsjJBhoF4rzHjFUR3XizMg118x/5eBZWkcmfVzSEWIQJ+bN2Lz4uJ7I2CAqnJV1zq3GZSX6F7AAwon83ZVA6UR6m0OrSpWOp+K8r9h0pbFHzNLK9QCaM6s2M1f8f05NOiCIm/zbXMNkrM1O0jj1RfoB7oXgTvyFpkRHPMdt/afRBpRCOOABMkLUh2BsOdaso3LIDm+CeOlTiwC4MjDejog5qqydwewDbaboAb/1mHr8HczFGhvMEMEAmdKfi0ESUQVeD7nIOkURnhxHS6jwWuFN1dC2cMR8Nwow94RWFA4JG/d5R3FePmxOpqMn2zgnqVgCocvWcETkjCyBIhYNiffwJgEnuyJmayXhNHBuX1BXScwLvaVdkAXQTszuY0jQyXS/SNX9GfhJKc0e/bb4torWIJmorSB8BDdEE7ynMdNzRspgEtFAx9r67j/x0tRZWiByppp3EF0uPkCKRAfY3oBxp7x9lss=
  - secure: Nrb4dNctsgyiYohr1RVQP4D3PKBaP35m9flo9zqxni5bmQxuc+Jm5CQyBM7UokmCykpTCUXIemSf90D18Ax30gQuhIa+MmlXxax/Fn2cCVK+e/DNTFfhJup+94ptNR6aMTtZRThhrtePk0A8k3gf8Y3M3aAqQZhZL5S8XZM2c3qfWALi1beFD+WAaZLcO9AlNy3/J/PbevoNc0svo6Q7WxxezObIOtztxj6zi+jX7D1LNep/VVrEOGtittsIIvq/Si8dquU4lNl1ZBldXs3zNA09DSVEkWd4dNAy527j1A9Sdsy01XxCZljIzOWUlyMqAZBF8I4a5CF2t7hLCVf48z0Os67tedSZL/M8mWR96tES81b8FxwKksVl4at/eXiUB2Dy485/BfTbgKaqWFYcDvokZmmy9cfwk+LnyoZBMlkoUn8mTYyioG2WBwWmb2HdQy6ErWUEppD9GcRrN4rGqQI2/8oJDYGsTkzjxxgZdau2ONrk803p3uJtPwKa7FKaRGoy7gAg5H0ExEABH9KS7G4gQo7AtkCqj2NlbtLc7L8PT/1CLIF+1aHC7zQlAC9Sr/q2tlulMLq1VTVDS6O1sOqKQm+OU3V7X4Zajs82OcG9yXJEulCdhBfKcq33ofE8ZdIOc3Av2JKVyy1g6fKYyCvxamvrHGhv6/bCTMjg6q8=
